//
//  MatchListWorker.swift
//  Brasileirao
//
//  Created by Fabio Martinez on 08/01/2019.
//  Copyright (c) 2018 Fabio Martinez. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit


class MatchListWorker
{
    var apiService = APIService.shared
    var realmService = RealmService.shared

    func fetchMatches(round: Int, completionHandler: @escaping (Any) -> Void)
    {
        apiService.getMatches(round: round, completion: { result in
            if let matches = result as? [Match] {
                self.saveMatches(matches: matches)
            }
            completionHandler(result)
        })
    }

    func saveMatches(matches: [Match]) {
        realmService.saveMatches(matches: matches)
    }

    func loadMatches() -> [Match] {
        return realmService.loadMatches()
    }
    
}
