//
//  MatchDetailsWireframe.swift
//  Brasileirao
//
//  Created by Fabio Martinez on 26/01/19.
//  Copyright (c) 2019 Fabio Martinez. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class MatchDetailsWireframe: BaseWireframe {

    // MARK: - Private properties -

    private let _storyboard = UIStoryboard(name: "Main", bundle: nil)

    // MARK: - Module setup -

    init(match: Match) {
        let moduleViewController = _storyboard.instantiateViewController(ofType: MatchDetailsViewController.self)
        super.init(viewController: moduleViewController)
        
        let interactor = MatchDetailsInteractor()
        let presenter = MatchDetailsPresenter(wireframe: self, view: moduleViewController, interactor: interactor, match: match)
        moduleViewController.presenter = presenter
    }

}

// MARK: - Extensions -

extension MatchDetailsWireframe: MatchDetailsWireframeInterface {

    func navigate(to option: MatchDetailsNavigationOption) {
    }
}
