//
//  MatchDetailsInterfaces.swift
//  Brasileirao
//
//  Created by Fabio Martinez on 26/01/19.
//  Copyright (c) 2019 Fabio Martinez. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

enum MatchDetailsNavigationOption {
}

protocol MatchDetailsWireframeInterface: WireframeInterface {
    func navigate(to option: MatchDetailsNavigationOption)
}

protocol MatchDetailsViewInterface: ViewInterface {
    func displayMatchDetailsTitle(screenTitle: String)
    func displayFetchedBids()
    func hideMessage()
}

protocol MatchDetailsPresenterInterface: PresenterInterface {
    func fetchBids()
    func numberOfItems() -> Int
    func item(at indexPath: IndexPath) -> MatchDetailsCellType
}

protocol MatchDetailsInteractorInterface: InteractorInterface {
    func fetchBids(_ url: String, completionHandler: @escaping (Any) -> Void)
}

protocol BidViewItemInterface {
    
    var period:     String  { get }
    var validTime:  String  { get }
    var title:      String  { get }
    var text:       String  { get }
}

enum MatchDetailsCellType {
    case matchCell(cellViewModel: MatchViewItemInterface)
    case bidCell(cellViewModel: BidViewItemInterface)
    case bidToBidCell
    case loadingCell
}
