//
//  MatchDetailsInteractor.swift
//  Brasileirao
//
//  Created by Fabio Martinez on 26/01/19.
//  Copyright (c) 2019 Fabio Martinez. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation

final class MatchDetailsInteractor {
    var apiService   = APIService.shared
}

// MARK: - Extensions -

extension MatchDetailsInteractor: MatchDetailsInteractorInterface {
    func fetchBids(_ url: String, completionHandler: @escaping (Any) -> Void) {
        apiService.getMatchResume(url: url, completion: { result in
            completionHandler(result)
        })
    }
}
