//
//  MatchDetailsViewController.swift
//  Brasileirao
//
//  Created by Fabio Martinez on 26/01/19.
//  Copyright (c) 2019 Fabio Martinez. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class MatchDetailsViewController: UIViewController {

    // MARK: - Public properties -
    @IBOutlet weak var tableView: UITableView!
    var presenter: MatchDetailsPresenterInterface!
    var alertView = AlertMessageView()
    
    // MARK: - Lifecycle -

    override func viewDidLoad() {
        super.viewDidLoad()
        configureView()
        configureTable()
        presenter.viewDidLoad()
    }
    
    override func viewWillDisappear(_ animated: Bool) {
        super.viewWillDisappear(animated)
        presenter.viewWillDisappear(animated: animated)
    }
    
    private func configureView() -> (Void) {
        self.alertMessage = self.makeShowMsgView()
        let window = UIApplication.shared.keyWindow!
        window.addSubview(self.alertView)
        window.bringSubviewToFront(self.alertView)
        
    }
    
    func configureTable() -> (Void) {
        let bidNib = UINib(nibName: BidTableViewCell.cellIdentifier(), bundle: nil)
        let LoadingNib = UINib(nibName: LoadingTableViewCell.cellIdentifier(), bundle: nil)
        let matchNib = UINib(nibName: MatchTableViewCell.cellIdentifier(), bundle: nil)
        let bidToBidNib = UINib(nibName: BidToBidTableViewCell.cellIdentifier(), bundle: nil)
        self.tableView.register(matchNib, forCellReuseIdentifier: MatchTableViewCell.cellIdentifier())
        self.tableView.register(bidNib, forCellReuseIdentifier: BidTableViewCell.cellIdentifier())
        self.tableView.register(LoadingNib, forCellReuseIdentifier: LoadingTableViewCell.cellIdentifier())
        self.tableView.register(bidToBidNib, forCellReuseIdentifier: BidToBidTableViewCell.cellIdentifier())
        self.tableView.rowHeight = UITableView.automaticDimension
        self.tableView.estimatedRowHeight = BidTableViewCell.heightForRow()
    }

}

// MARK: - Extensions -

extension MatchDetailsViewController: MatchDetailsViewInterface {
   
    func displayMatchDetailsTitle(screenTitle: String) {
        title = screenTitle
    }
    
    func displayFetchedBids() {
        tableView.reloadData()
    }
    
    func hideMessage() {
        alertView.hideAlertMessageAnim()
    }
}

extension MatchDetailsViewController: UITableViewDataSource {
    
    func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
        return presenter.numberOfItems()
    }
    
    func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
        
        switch presenter.item(at: indexPath) {
            case .matchCell(let matchViewModel):
                let cell = tableView.dequeueReusableCell(withIdentifier: MatchTableViewCell.cellIdentifier(), for: indexPath) as! MatchTableViewCell
                cell.configure(with: matchViewModel, hasSeparatorView: false)
                return cell
            case .bidToBidCell:
                let cell = tableView.dequeueReusableCell(withIdentifier: BidToBidTableViewCell.cellIdentifier(), for: indexPath) as! BidToBidTableViewCell
                return cell
            case .bidCell(let bidViewModel):
                let cell = tableView.dequeueReusableCell(withIdentifier: BidTableViewCell.cellIdentifier(), for: indexPath) as! BidTableViewCell
                cell.configure(withViewModel: bidViewModel)
                return cell
            case .loadingCell:
                let cell = tableView.dequeueReusableCell(withIdentifier: LoadingTableViewCell.cellIdentifier(), for: indexPath) as! LoadingTableViewCell
                return cell
        }
        
    }
    
}

extension MatchDetailsViewController: AlertMessageDialogPresenter {
    var alertMessage: AlertMessageView {
        get {
            return self.alertView
        }
        set(alert) {
            self.alertView = alert
        }
    }
}
