//
//  MatchListInterfaces.swift
//  Brasileirao
//
//  Created by Fabio Martinez on 22/01/19.
//  Copyright (c) 2019 Fabio Martinez. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

enum MatchListNavigationOption {
    case matchDetails(Match)
}

protocol MatchListWireframeInterface: WireframeInterface {
    func navigate(to option: MatchListNavigationOption)
}

protocol MatchListViewInterface: ViewInterface {
    func displayMessage(bgColor: UIColor, msg: String)
    func displayFetchedMatches(screentitle: String)
    func setLoadingVisible(_ visible: Bool)
}

protocol MatchListPresenterInterface: PresenterInterface {
    func fetchMatches()
    func fetchNextMatches()
    func fetchPreviusMatches()
    func handleMatchSelection(at indexPath: IndexPath)
    func item(at indexPath: IndexPath) -> MatchViewItemInterface
    func numberOfItems() -> Int
}

protocol MatchListInteractorInterface: InteractorInterface {
    func fetchMatches(round: Int, completionHandler: @escaping (Any) -> Void)
    func saveMatches(matches: [Match]) /////////apagar
    func loadMatches() -> [Match] /////////apagar
    
}


protocol MatchViewItemInterface {
    
    var title:             NSAttributedString? { get }
    var scoreBoard:        NSAttributedString? { get }
    var homeClubName:      String?             { get }
    var guestClubName:     String?             { get }
    var guestClubImageUrl: URL?                { get }
    var homeClubImageUrl:  URL?                { get }
    var matchBidsUrl:      String?             { get }

}
