//
//  MatchListInteractor.swift
//  Brasileirao
//
//  Created by Fabio Martinez on 22/01/19.
//  Copyright (c) 2019 Fabio Martinez. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation

final class MatchListInteractor {
    var apiService   = APIService.shared
    var realmService = RealmService.shared
}

// MARK: - Extensions -

extension MatchListInteractor: MatchListInteractorInterface {
    
    func fetchMatches(round: Int, completionHandler: @escaping (Any) -> Void)
    {
        apiService.getMatches(round: round, completion: { result in
            if let matches = result as? [Match] {
                self.saveMatches(matches: matches)
            }
            completionHandler(result)
        })
    }
    
    func saveMatches(matches: [Match]) {
        realmService.saveMatches(matches: matches)
    }
    
    func loadMatches() -> [Match] {
        return realmService.loadMatches()
    }
    
}
