//
//  MatchDetailsWorker.swift
//  Brasileirao
//
//  Created by Fabio Martinez on 08/01/2019.
//  Copyright (c) 2018 Fabio Martinez. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class MatchDetailsWorker {
    var apiService = APIService.shared
    
    func fetchBids(url: String, completionHandler: @escaping (Any) -> Void) {
        apiService.getMatchResume(url: url, completion: { result in
            completionHandler(result)
        })
    }
}
